name: Musings
favicon: null
layout_spectrum: 0.5861679464578629
typography_spectrum: 0.04290805128403008
title: New Years Eve 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.21611305978149176
  lightness: 0.9941900398116559
  saturation: 0.8283589063212276
  rhythmicContrast: 0.787680960027501
purpose: []
